spring:
  flyway:
    enabled: false

  profiles:
    active: prod

  thymeleaf:
    cache: false
    encoding: UTF-8

  devtools:
    restart:
      enabled: true
      exclude: static/**, templates/**, i18n/**

  jpa:
    show-sql: ${hibernate.show-sql}
    hibernate:
      ddl-auto: ${hibernate.ddl-auto}
      format-sql: ${hibernate.format-sql}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://${db.hostname}:${db.port}/${db.schema}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8
    username: ${db.username}
    password: ${db.password}

    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 200
        one-indexed-parameters: false
        page-parameter: page
        prefix:
        qualifier-delimiter: _
        size-parameter: size
      sort:
        sort-parameter: sort

server:
  debug: true
#  http:
#    port: 8082
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
#    key-store-password: techblog
#    key-alias: techblog

logging:
  level:
    org.springframework.web: INFO
    com.techblog: DEBUG